/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.HarvestingAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Farmer.Farmer;
import Business.Organization.HarvestingOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HarvestingWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aksha
 */
public class HarvestingAdminWorkAreaPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private HarvestingOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private HarvestingOrganization harvestingOrganization;
    private EcoSystem system;
    //Farmer farmer = HarvestingAdminWorkAreaPanel.dummyFarmer();
    /**
     * Creates new form SowingAdminWorkAreaPanel
     */
    

    public HarvestingAdminWorkAreaPanel(JPanel userProcessContainer, UserAccount account, HarvestingOrganization harvestingOrganization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
       //this.organization = organization;
       this.harvestingOrganization = harvestingOrganization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
//        dummyFarmer();
        populateTable();
    }
//public static Farmer dummyFarmer() {
//    Farmer farmer = new Farmer();
//    farmer.setFarmerId(10000000);
//    farmer.setFarmerName("Akshay");
//    farmer.setFarmSize(100);
//    farmer.setCropName("Rice");
//    farmer.setCropQuantity(123);
//    farmer.setExpectedDays(100);
//    farmer.setIrrigationDays(99);
//    farmer.setFertilizerPrice(10);
//    farmer.setHarvestQuantity(100);
//    farmer.setSowingAdminId(1000);
//    farmer.setIrrigationAdminId(1001);
//    farmer.setFertilizerAdminId(1002);
//    farmer.setHarvestingAdminId(1003);
//    farmer.setTransportAdminId(1004);
//    farmer.setStatus("Harvesting completed");
//    farmer.getUserAccount().setUsername("akshay");
//    
//    return farmer;
//}
    private void populateTable() 
    {
        DefaultTableModel model = (DefaultTableModel) farmersCreatedJTable.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest workRequest : harvestingOrganization.getWorkQueue().getWorkRequestList())
        {
            HarvestingWorkRequest harvestingWorkRequest = (HarvestingWorkRequest) workRequest;
            Object[] row = new Object[6];
            row[0] = ((Farmer)harvestingWorkRequest.getData()).getFarmerId();
            row[1] = ((Farmer)harvestingWorkRequest.getData()).getFarmerName();
            row[2] = harvestingWorkRequest.getData();
//            row[2] =((Farmer)sowingWorkRequest.getData()).getUserAccount().getUsername();
//            row[3] = ((Farmer)sowingWorkRequest.getData()).getSowingAdminId();
//            row[4] = ((Farmer)sowingWorkRequest.getData());
//            row[5] = sowingWorkRequest;
            
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        farmersCreatedJTable = new javax.swing.JTable();
        assignToMeJBtn = new javax.swing.JButton();
        monitorJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        farmersCreatedJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Farmer ID", "Farmer Name", "Object"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(farmersCreatedJTable);
        if (farmersCreatedJTable.getColumnModel().getColumnCount() > 0) {
            farmersCreatedJTable.getColumnModel().getColumn(2).setMinWidth(0);
            farmersCreatedJTable.getColumnModel().getColumn(2).setPreferredWidth(0);
            farmersCreatedJTable.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        assignToMeJBtn.setText("Assign to me");
        assignToMeJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeJBtnActionPerformed(evt);
            }
        });

        monitorJBtn.setText("Monitor Assigned Farmers");
        monitorJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitorJBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Harvesting Employee Work Area Panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assignToMeJBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(monitorJBtn))
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignToMeJBtn)
                    .addComponent(monitorJBtn))
                .addContainerGap(245, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void monitorJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorJBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("HarvestingAdminMonitorAreaJPanel", new HarvestingAdminMonitorAreaJPanel(userProcessContainer, userAccount, harvestingOrganization, enterprise, system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_monitorJBtnActionPerformed

    private void assignToMeJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeJBtnActionPerformed
        // TODO add your handling code here:
       
        int selectedRow = farmersCreatedJTable.getSelectedRow();
        
        if (selectedRow < 0)
        {
       
           JOptionPane.showMessageDialog(null, "Please Select a Row");
            return;
        }
        Farmer farmer = (Farmer)farmersCreatedJTable.getValueAt(selectedRow, 2);
        for(WorkRequest workRequest : harvestingOrganization.getWorkQueue().getWorkRequestList())
        {
            workRequest.setFarmerUserId(farmer.getFarmerId());
            userAccount.getWorkQueue().getWorkRequestList().add(workRequest);
            
        }
         JOptionPane.showMessageDialog(null, "Farmer assigned to me Successfully!!");
         return;
         
//        HarvestingWorkRequest harvestingWorkRequest = new HarvestingWorkRequest();
//        for (WorkRequest workRequest : userAccount.getWorkQueue().getWorkRequestList())
//        {
//            if(((Farmer)((HarvestingWorkRequest)workRequest).getData()).getFarmerId()==farmer.getFarmerId())
//            {
//                JOptionPane.showMessageDialog(null, "Farmer is already assigned to me!!");
//                return;  
//            }
//        }
//        
//        harvestingWorkRequest.setReceiver(userAccount);
//        harvestingWorkRequest.setRequestDate(new Date());
//        harvestingWorkRequest.setStatus("Fertilization Done");
//        harvestingWorkRequest.setData(farmer);
//        
//        harvestingOrganization.getWorkQueue().getWorkRequestList().add(harvestingWorkRequest);
//        userAccount.getWorkQueue().getWorkRequestList().add(harvestingWorkRequest);
        
                              
    }//GEN-LAST:event_assignToMeJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignToMeJBtn;
    private javax.swing.JTable farmersCreatedJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton monitorJBtn;
    // End of variables declaration//GEN-END:variables
}
