/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.FarmerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Farmer.Farmer;
import Business.Initialization;
import Business.Organization.FarmerOrganization;
import Business.Organization.LabOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import userinterface.AdministrativeRole.ManageOrganizationJPanel;
import userinterface.HarvestingAdminRole.HarvestingAdminMonitorAreaJPanel;

/**
 *
 * @author jocel
 */
public class FarmerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FarmerWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private FarmerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    public EcoSystem system;
    private Farmer farmer;
    public Initialization initialization;
    public LabOrganization labOrganization;
    public FarmerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, FarmerOrganization organization, Enterprise enterprise, EcoSystem system, Farmer farmer,LabOrganization labOrganization) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.farmer  = farmer;
        this.system = system;
        initialization = new Initialization();
        this.system=system;
        this.labOrganization = labOrganization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sowingJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        irrigationJBtn = new javax.swing.JButton();
        fertilizingJBtn = new javax.swing.JButton();
        harvestingJBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        sowingJBtn.setText("Sowing Task");
        sowingJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sowingJBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area - Farmer Role");

        irrigationJBtn.setText("Irrigation Task");
        irrigationJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                irrigationJBtnActionPerformed(evt);
            }
        });

        fertilizingJBtn.setText("Fertilizing Task");
        fertilizingJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fertilizingJBtnActionPerformed(evt);
            }
        });

        harvestingJBtn.setText("Harvesting Task");
        harvestingJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                harvestingJBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Farmer first panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(irrigationJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fertilizingJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(harvestingJBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE))
                            .addComponent(sowingJBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addGap(68, 68, 68)
                .addComponent(sowingJBtn)
                .addGap(18, 18, 18)
                .addComponent(irrigationJBtn)
                .addGap(18, 18, 18)
                .addComponent(fertilizingJBtn)
                .addGap(18, 18, 18)
                .addComponent(harvestingJBtn)
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sowingJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sowingJBtnActionPerformed
        // TODO add your handling code here:
        SowingTaskWorkAreaJPanel sowingTaskWorkAreaJPanel = null;
        try {
            sowingTaskWorkAreaJPanel = new SowingTaskWorkAreaJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),initialization,farmer);
        } catch (IOException ex) {
            Logger.getLogger(FarmerWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        userProcessContainer.add("sowingTaskWorkAreaJPanel", sowingTaskWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_sowingJBtnActionPerformed

    private void irrigationJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_irrigationJBtnActionPerformed
        // TODO add your handling code here:
         IrrigationTaskWorkAreaJPanel irrigationTaskWorkAreaJPanel = new IrrigationTaskWorkAreaJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),farmer);
        userProcessContainer.add("irrigationTaskWorkAreaJPanel", irrigationTaskWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_irrigationJBtnActionPerformed

    private void fertilizingJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fertilizingJBtnActionPerformed
        // TODO add your handling code here:
         FertilizingTaskWorkAreaJPanel fertilizingTaskWorkAreaJPanel = new FertilizingTaskWorkAreaJPanel(userProcessContainer, enterprise.getOrganizationDirectory(),initialization,farmer,system,labOrganization);
        userProcessContainer.add("fertilizingTaskWorkAreaJPanel", fertilizingTaskWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_fertilizingJBtnActionPerformed

    private void harvestingJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_harvestingJBtnActionPerformed
        // TODO add your handling code here:
        HarvestingTaskWorkAreaJPanel harvestingTaskWorkAreaJPanel = new HarvestingTaskWorkAreaJPanel(userProcessContainer, enterprise.getOrganizationDirectory(), system, farmer);
        userProcessContainer.add("harvestingTaskWorkAreaJPanel", harvestingTaskWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_harvestingJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fertilizingJBtn;
    private javax.swing.JButton harvestingJBtn;
    private javax.swing.JButton irrigationJBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton sowingJBtn;
    // End of variables declaration//GEN-END:variables
}
