/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SowingAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Farmer.Farmer;
import Business.Organization.SowingOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.SowingWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aksha
 */
public class SowingAdminWorkAreaPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private SowingOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    /**
     * Creates new form SowingAdminWorkAreaPanel
     */
    

    public SowingAdminWorkAreaPanel(JPanel userProcessContainer, UserAccount userAccount, SowingOrganization sowingOrganization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = sowingOrganization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane = new javax.swing.JScrollPane();
        farmersCreatedJTable = new javax.swing.JTable();
        assignToMeJBtn = new javax.swing.JButton();
        monitorJBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        farmersCreatedJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Farmer ID", "Farmer Name", "Username", "Reporting Sowing Admin", "Object", "Object"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane.setViewportView(farmersCreatedJTable);
        if (farmersCreatedJTable.getColumnModel().getColumnCount() > 0) {
            farmersCreatedJTable.getColumnModel().getColumn(4).setMinWidth(0);
            farmersCreatedJTable.getColumnModel().getColumn(4).setPreferredWidth(0);
            farmersCreatedJTable.getColumnModel().getColumn(4).setMaxWidth(0);
            farmersCreatedJTable.getColumnModel().getColumn(5).setMinWidth(0);
            farmersCreatedJTable.getColumnModel().getColumn(5).setPreferredWidth(0);
            farmersCreatedJTable.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        assignToMeJBtn.setText("Assign to me");
        assignToMeJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignToMeJBtnActionPerformed(evt);
            }
        });

        monitorJBtn.setText("Monitor Assigned Farmers");
        monitorJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitorJBtnActionPerformed(evt);
            }
        });

        jLabel1.setText("Sowing Employee Work Area Panel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(assignToMeJBtn)
                                .addGap(89, 89, 89)
                                .addComponent(monitorJBtn)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assignToMeJBtn)
                    .addComponent(monitorJBtn))
                .addContainerGap(145, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void monitorJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorJBtnActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("SowingAdminMonitorAreaJPanel", new SowingAdminMonitorAreaJPanel(userProcessContainer, userAccount, organization, enterprise));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_monitorJBtnActionPerformed

    private void assignToMeJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignToMeJBtnActionPerformed
        int selectedRow = farmersCreatedJTable.getSelectedRow();
        
        if (selectedRow < 0)
        {
           JOptionPane.showMessageDialog(null, "Please Select a Row");
           return;
        }
        Farmer farmer = (Farmer)farmersCreatedJTable.getValueAt(selectedRow, 4);
        farmer.setSowingAdminId(userAccount.getEmployee().getId());
        //SowingWorkRequest sowingWorkRequest = new SowingWorkRequest();
        if(userAccount.getWorkQueue().getWorkRequestList().isEmpty())
        {
            SowingWorkRequest sowingWorkRequest = (SowingWorkRequest) farmersCreatedJTable.getValueAt(selectedRow, 5);
            userAccount.getWorkQueue().getWorkRequestList().add(sowingWorkRequest);
        }
        else
        {
            for (WorkRequest workRequest : userAccount.getWorkQueue().getWorkRequestList())
            {
                if(((Farmer)((SowingWorkRequest)workRequest).getData()).getFarmerId()==farmer.getFarmerId())
                {
                    JOptionPane.showMessageDialog(null, "Farmer is already assigned to me!!");
                    return;  
                }
                else
                {
                    
                }
                
            }
            //If i place this above code in else then concurrentModificationException
            SowingWorkRequest sowingWorkRequest = (SowingWorkRequest) farmersCreatedJTable.getValueAt(selectedRow, 5);
            userAccount.getWorkQueue().getWorkRequestList().add(sowingWorkRequest);
        }
        
        
        //sowingWorkRequest.setReceiver(userAccount);
        //sowingWorkRequest.setRequestDate(new Date());
        //sowingWorkRequest.setStatus("Sowing not started");
        
        //organization.getWorkQueue().getWorkRequestList().add(sowingWorkRequest);
        
        JOptionPane.showMessageDialog(null, "Farmer assigned to me Successfully!!");
        
        populateTable();
    }//GEN-LAST:event_assignToMeJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignToMeJBtn;
    private javax.swing.JTable farmersCreatedJTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton monitorJBtn;
    // End of variables declaration//GEN-END:variables

    private void populateTable() 
    {
        DefaultTableModel model = (DefaultTableModel) farmersCreatedJTable.getModel();
        
        model.setRowCount(0);
        
        for (WorkRequest workRequest : organization.getWorkQueue().getWorkRequestList())
        {
            SowingWorkRequest sowingWorkRequest = (SowingWorkRequest) workRequest;
            Object[] row = new Object[6];
            row[0] = ((Farmer)sowingWorkRequest.getData()).getFarmerId();
            row[1] = ((Farmer)sowingWorkRequest.getData()).getFarmerName();
            row[2] =((Farmer)sowingWorkRequest.getData()).getUserAccount().getUsername();
            row[3] = ((Farmer)sowingWorkRequest.getData()).getSowingAdminId();
            row[4] = ((Farmer)sowingWorkRequest.getData());
            row[5] = sowingWorkRequest;
            
            
            model.addRow(row);
        }
    }
}
