/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.EcoSystem;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author aksha
 */
public class ProfitFromEnterprise extends javax.swing.JPanel {
private JPanel userProcessContainer;
private EcoSystem system;
    /**
     * Creates new form ProfitFromEnterprise
     */
    
    ProfitFromEnterprise(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        
        DefaultCategoryDataset barChartDataDist = new DefaultCategoryDataset();
        barChartDataDist.setValue(20000, "Profit", "Distributor");
        barChartDataDist.setValue(15000, "Profit", "Lab");
        barChartDataDist.setValue(30000, "Profit", "Transport");
        JFreeChart barChart = ChartFactory.createBarChart("Walmart India Profit", "Enterprise", "Profit in $", barChartDataDist, PlotOrientation.VERTICAL, false, true , false );
        CategoryPlot barChrt = barChart.getCategoryPlot();
        barChrt.setRangeGridlinePaint(Color.RED);
        
        ChartPanel barPanel = new ChartPanel(barChart);
        indiaPanel.removeAll();
        indiaPanel.add(barPanel);
        indiaPanel.validate();
        
       
        DefaultCategoryDataset barChartDataBos = new DefaultCategoryDataset();
        barChartDataBos.setValue(20000, "Profit", "Distributor");
        barChartDataBos.setValue(15000, "Profit", "Lab");
        barChartDataBos.setValue(30000, "Profit", "Transport");
        JFreeChart barChartBos = ChartFactory.createBarChart("Walmart Boston Profit", "Enterprise", "Profit in $", barChartDataBos, PlotOrientation.VERTICAL, false, true , false );
        CategoryPlot barChrtBos = barChartBos.getCategoryPlot();
        barChrtBos.setRangeGridlinePaint(Color.RED);
        
        ChartPanel barPanelBos = new ChartPanel(barChartBos);
        bostonPanel.removeAll();
        bostonPanel.add(barPanelBos);
        bostonPanel.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        indiaPanel = new javax.swing.JPanel();
        backJButton = new javax.swing.JButton();
        bostonPanel = new javax.swing.JPanel();

        indiaPanel.setLayout(new java.awt.BorderLayout());

        backJButton.setText("<< Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        bostonPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(indiaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bostonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(backJButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(indiaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bostonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(backJButton)
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        userProcessContainer.remove(this);
        //                Component[] componentArray = userProcessContainer.getComponents();
        //                Component component = componentArray[componentArray.length - 1];
        //                SystemAdminWorkAreaJPanel sysAdminwjp = (SystemAdminWorkAreaJPanel) component;
        //        sysAdminwjp.populateTree();

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JPanel bostonPanel;
    private javax.swing.JPanel indiaPanel;
    // End of variables declaration//GEN-END:variables
}
